// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5SZtYHksqfRuUQqW4kYfPoJdsS2o4ZZk',
    appId: '1:564327617692:web:4619dc726e8a2d326b4959',
    messagingSenderId: '564327617692',
    projectId: 'authsetup-5a3e3',
    authDomain: 'authsetup-5a3e3.firebaseapp.com',
    storageBucket: 'authsetup-5a3e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBESGqIyHp_0Ag12obrESFbaEtHAmAz0Xs',
    appId: '1:564327617692:android:21b102d86a74df556b4959',
    messagingSenderId: '564327617692',
    projectId: 'authsetup-5a3e3',
    storageBucket: 'authsetup-5a3e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArWf3yowv379QQb3d7V69Vv_JLZFEY6QA',
    appId: '1:564327617692:ios:8cccf09d651754cb6b4959',
    messagingSenderId: '564327617692',
    projectId: 'authsetup-5a3e3',
    storageBucket: 'authsetup-5a3e3.firebasestorage.app',
    iosClientId: '564327617692-kidqn3bnblf9nhke8d2s6anoouodi06m.apps.googleusercontent.com',
    iosBundleId: 'com.example.authpractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArWf3yowv379QQb3d7V69Vv_JLZFEY6QA',
    appId: '1:564327617692:ios:8cccf09d651754cb6b4959',
    messagingSenderId: '564327617692',
    projectId: 'authsetup-5a3e3',
    storageBucket: 'authsetup-5a3e3.firebasestorage.app',
    iosClientId: '564327617692-kidqn3bnblf9nhke8d2s6anoouodi06m.apps.googleusercontent.com',
    iosBundleId: 'com.example.authpractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5SZtYHksqfRuUQqW4kYfPoJdsS2o4ZZk',
    appId: '1:564327617692:web:bafe72ee395d158b6b4959',
    messagingSenderId: '564327617692',
    projectId: 'authsetup-5a3e3',
    authDomain: 'authsetup-5a3e3.firebaseapp.com',
    storageBucket: 'authsetup-5a3e3.firebasestorage.app',
  );
}
